# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c99455b11d3ff9ec4a23ef036e74f8a33680a5e6d7842daaef27822fb030b642f26f9c73005fc3c11e6555d6e03844445ad23ae22ca2a383af5aa4bd318dcb5d

test:
  secret_key_base: 7ea27ecd2f5084c6aee70772d8b853b3b35878c75e5ddb876902fa9c4eef73b5b858adfa96582db9637e8304597764a784ce81d951d6f7a3b309ce951a6e7927

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
